first_project1/first_app1/urls.py
from django.urls import path
from . import views
app_name = 'first_app1'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_login', views.user_login, name='user_login'),
    path('register', views.register, name='register'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('homepage', views.homepage, name='homepage'),
 
]

first_project1/first_project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app1.urls')),
]

first_project1/first_app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Userprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    ## additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username

first_project1/first_app1/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app1.models import Userprofile

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        

class Userprofileform(forms.ModelForm):
    class Meta():
        model = Userprofile
        fields = ('portfolio_site', 'profile_pic')

first_project1/first_app1/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from first_app1.forms import Userform, Userprofileform
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'first_app1/index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = Userform(data=request.POST)
        profile_form = Userprofileform(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors)
            print(profile_form.errors)
    else:
        user_form = Userform()
        profile_form = Userprofileform()
    return render(request, 'first_app1/registration.html', {'user_form': user_form, 'profile_form': profile_form,'registered': registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_app1:index'))

def homepage(request):
    return render(request, 'first_app1/homepage.html')


def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('first_app1:homepage'))
            else:
                return HttpResponse('Your account is inactive. Please contact admin.')
        else:
            return HttpResponse('Invalid username or password.')
    else:
        return render(request, 'first_app1/login.html',{})
    
          
    

first_project1/templates/first_app1/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'admin:index' %}">Index Page </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'first_app1:register' %}">register</a>
                </li>
               {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'first_app1:user_logout' %}">logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'first_app1:user_login' %}">login</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
          <div class="container">
            {% block body_block %}
            {% endblock %}
          </div>
    </body>
</html>

first_project1/templates/first_app1/homepage.html
{% extends 'first_app1/base.html' %}
{% block body_block %}
<h1>Welcoome to the Home page. Log in Successful</h1>

{% endblock %}

first_project1/templates/first_app1/index.html
<!DOCTYPE html>
{% extends "first_app1/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django level 4</h1>
</div>
{% endblock %}

first_project1/templates/first_app1/login.html
{% extends 'first_app1/base.html' %}
{% block body_block%}
<div class="container">
    <h1>Please login</h1>
    <div class="jumbotron">
        <form action="{% url 'first_app1:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <input type="submit" value="Login">
        </form>
    </div>
</div>
{% endblock %}

first_project1/templates/first_app1/registration.html
<!DOCTYPE html>
{% extends "first_app1/base.html" %}
{% load static %}
{% block body_block %}
    <div class="container">
        {% if registered %}
        <h1>Thank you for registering</h1>
        {% else %}
        <h1>Please register</h1>
        <h3>Please fill out the form below</h3>
        <div class="jumbotron">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>
        </div>
        {% endif %}
    </div>
{%endblock%}